import { Comfortaa } from "next/font/google"
import { Metadata } from "next"
import "./globals.css"

const comfortaa = Comfortaa({
    variable: "--font-comfortaa",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${comfortaa.variable} antialiased`}>{children}</body>
        </html>
    )
}
